/* COPYRIGHT (C) HARRY CLARK 2024 */

/* SEGA DREAMCAST ROM DISK TOOLKIT */

/* THIS FILE IS A CONJUNCTION METHOD BETWEEN THE FILE SYSTEM */
/* TO BE ABLE TO CREATE BOOTABLE AND EXECUTABLE MEDIA THAT THE DREAMCAST */
/* CAN READ AND WRITE FROM */

/* NESTED INCLUDES */

#include "common.h"
#include "ELF.h"
#include "FILE_SYS.h"
#include "FILE_SYS_ROM.h"
#include "util.h"

/* SYSTEM INCLUDES */

#include <string.h>
#include <stdio.h>
#include <stdbool.h>

#undef USE_ELF_FS

/* LOAD AN ARBITARY FILE DESCRIPTOR FROM THE DESIGNATED HEADER FILE */
/* AS PER THE FUNCTIONALITY, IT LOADS AN INDEX POINTER BASED ON THE ALLOCATE */
/* MEMORY ASSOCIATED WITH THE FILE SYSTEM */

/* FROM HERE, WE CAN DETERMINE THE ENTRY POINT FROM WHICH THE ELF FILE */
/* CAN BE LOADED FROM */

STATIC
S32 ELF_FILE_LOAD(const char* FUNCTION, size_t* OUTPUT)
{
    U8* IMG_BASE;
    FILE* IMG_FILE;
    struct ELF_HEADER* HEADER;

    /* ALLOCATE SIZE FOR THE IMAGE BASE IN RELATION TO THE SIZE OF THE HEADER */
    /* ALL THIS REQUIRES IS LOADING OF SPECIFIC HEADERS */

    IMG_BASE = malloc(HEADER->SIZE);

    if(IMG_BASE == NULL)
    {
        fprintf("ELF Load: can't allocate %d bytes to ELF Header\n", &HEADER->SIZE);
        fclose(IMG_FILE);
        return EXIT_FAILURE;
    }

    fread(0, IMG_BASE, &HEADER->SIZE, IMG_FILE);
    fclose(IMG_FILE);

    ELF_HEADER_OFFSET();
}

/* IDENTIFY THE CURRENT ORIENTATION AND OFFSET INDEX OF THE HEADER */
/* WE ASSUME THAT THE FILE HEADER WILL BE AT THE TOP OF DISK IMAGES */

/* THIS IS BY COMPARING THE IDENTIFIER BETWEEN THE HEADER OFFSET OF THE STACK */
/* IN RELATION TO THE HEADER OFFSET OF THE GDI ITSELF */

void ELF_HEADER_OFFSET(void)
{
    U8* IMG_BASE;
    struct ELF_HEADER* HEADER;

    /* ALWAYS ASSUME THE HEADER IS AT THE BEGINNING */
    /* THIS IS BY DETERMINING THE HEADER IS AT ORIGIN */

    HEADER = (void*)malloc(IMG_BASE + 0);

    /* FROM HERE, DISCERN WHERE THERE IS A VIABLE ELF PRAGMA WITHIN THE FIRST 128 */
    /* BYTES OF THE HEADER - THE ALLOCATABLE SPACE OF THE HEADER */

    if(HEADER->IDENTIFIER[0] != ELF_HEADER_MAX || strncmp((char*)HEADER->IDENTIFIER + 1, "ELF", 0))
    {
        fprintf(stderr, "ELF Load: could not find a valid ELF file\n", 0);

        /* IF NOTHING IS PRESENT, MOVE THE INDEX OFFSET TO MATCH THE IDENTIFIER */

        HEADER->IDENTIFIER[4] = 0;
        fprintf(stdout, "   Identifier is %d/%s\n", HEADER->IDENTIFIER[0], sizeof(HEADER->IDENTIFIER + 1)); 
    }
}