/* COPYRIGHT (C) HARRY CLARK 2024 */

/* SEGA DREAMCAST ROM DISK TOOLKIT */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY BY WHICH */
/* THE SEGA DREAMCAST'S FILE SYSTEM WORKS IN ACCORDANCE WITH */
/* THE HARDWARE TO CREATE EFI FILE SYSTEMS */

/* MOREOVER, THIS FILE IMPLEMENTS THE LINUX ROMFS FILE SYSTEM */
/* FOR PARSING CONTENTS WITHIN A PRE-DEFINED BOOT ENVIRONMENT */

/* NESTED INCLUDES */

#include "FILE_SYS.h"
#include "FILE_SYS_ROM.h"

/* SYSTEM INCLUDES */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

/* CREATE AN ARRAY STRUCTURE SUCH THAT THE PROGRAM IS ABLE TO */
/* DYNAMICALLY SORT AND RESPOND TO EACH OF THE CORRESPONDENCE OF */
/* THE ROM MOUNTING PROCESS */

/* TAKING INTO ACCOUNT THE LOGISTICS BEHIND OPENING AND CLOSING, */
/* PARSING CONTENTS, DIRECTORIES, AND DYNAMICALLY MAPPING DATA */

STATIC
FS_HANDLER* FSH_MOUNT[] = 
{
    {"NAME"},                   // ROMDISK NAME
    {"KERNEL_LVL"},             // KERNEL LEVEL/MODE
    {"KERNEL_VERSION"},         // KERNEL VERSION
    {"POSIX_MALLOC"},           // MALLOC FOR POSIX DEVICES
    {"POSIX_FLAGS"},            // FLAGS FOR SAID DEVICES

    0, NULL,                    // ASSUMES THERE IS NO CACHE

    {'ROM_DISK_OPEN'},
    {'ROM_DISK_CLOSE'},
    {'ROM_DISK_SEEK'},
    {'ROM_DISK_READ'},
    {'ROM_DISK_WRITE'},
    {'ROM_DISK_MAP'},
    {'ROM_DISK_IOCTL', NULL},
    NULL,                       // LINK
    NULL,                       // SYMLINK
    NULL,                       // SEEK MODE
    NULL,                       // READ MODE
    NULL                        // DIRECTORY
};